name: Test and Lint CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: test_and_lint
      # env:
      #   AWS_ACCESS_KEY_ID: ${{ secrets.PERSONAL_AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.PERSONAL_AWS_SECRET_ACCESS_KEY }}
      #   AWS_DEFAULT_REGION: 'eu-west-2'
      run: |
        npm i
        npm run test
        npm run lint

# ToDo - deploy to dev & deploy to prod on tag

# name: deploy to prod on tag
# on:
#   push:
#     tags:
#       - "*"
# jobs:
#   test_and_lint:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14.x]
#     steps:
#     - run: echo "Branch is tagged!"