name: Test and Lint CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
    - run: npm i
    - run: npm run test
    - run: npm run lint

# ToDo - deploy to dev & deploy to prod on tag

# name: deploy to prod on tag
# on:
#   push:
#     tags:
#       - "*"
# jobs:
#   test_and_lint:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [14.x]
#     steps:
#     - run: echo "Branch is tagged!"